loop_n_poll/loop_n_poll/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

loop_n_poll/polls/urls.py
from django.urls import path

from . import views


# Чтобы обратиться в шаблонах к views.detail именно этого приложения,
# нужно дать ему имя:
app_name = 'polls'
# Теперь в любом шаблоне можно вызвать нужную функцию
# по тегу {% url 'polls:detail'}.

urlpatterns = [
    path('', views.index, name='index'),
    # Используем атрибут "name", чтобы обращаться к нему в html-шаблонах
    # и иметь возможность менять адрес только в этом файле.
    path('<int:question_id>', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote')
]

loop_n_poll/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    class Meta:
        verbose_name = 'вопрос'
        verbose_name_plural = 'вопросы'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

    class Meta:
        verbose_name = 'вариант'
        verbose_name_plural = 'варианты'

loop_n_poll/polls/views.py
from django.db.models import F
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Choice, Question


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # context — это словарь,
    # сопоставляющий имена переменных шаблона с объектами Python.
    context = {
        'latest_question_list': latest_question_list
    }
    return render(request, 'polls/index.html', context)

# Старая версия функции:
# def detail(request, question_id):
#     try:
#         question = Question.objects.get(pk=question_id)
#     except Question.DoesNotExist:
#         raise Http404('Question does not exist!')
#     return render(request, 'polls/detail.html', {'question': question})


# С шорткатом get_object_or_404():
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        # request.POST is a dictionary-like object that lets you access
        # submitted data by key name. In this case, request.POST['choice']
        # returns the ID of the selected choice, as a string.
        # request.POST values are always strings.
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form:
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice."
        })
    else:
        # selected_choice.votes += 1  # Если юзеры проголосуют одновременно,
        # им присвоится один и тот же номер...
        # Avoiding race conditions using F()
        selected_choice.votes = F('votes') + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(
            reverse('polls:results', args=(question.id,))
        )

loop_n_poll/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
  {% csrf_token %}
  <fieldset>
      <legend><h1>{{ question.question_text }}</h1></legend>
      {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
      {% for choice in question.choice_set.all %}
          <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
          {% comment %} 
            "forloop.counter" указывает, сколько раз тег "for" прошел цикл. 
          {% endcomment %}
          <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
      {% endfor %}
  </fieldset>
  <input type="submit" value="Vote">
  </form>

{% comment %}
Первая версия страницы:

<h1>Question №{{ question.id }}: {{ question.question_text }}</h1>
<ul>
  {% for choice in question.choice_set.all %}
      <li>{{ choice.choice_text }}</li>
  {% endfor %}
</ul> 
{% endcomment %}

loop_n_poll/polls/templates/polls/index.html
{% if latest_question_list %}
  <ul>
  {% for question in latest_question_list %}
    {% comment %} 
      Прямая ссылка в шаблоне потребует её изменения при изменении адреса
    <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
      
      Можно использовать тег {% url %} — добавляем атрибут "name" к path(),
      в шаблоне пишем 'имя_приложения:name_функции' и меняем ссылки тольков urls.py
    {% endcomment %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <p>No polls are available.</p>
{% endif %}

loop_n_poll/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>